apiVersion: v1
kind: ConfigMap
metadata:
  name: mk1-config
data:
  POS_DB_URL: "jdbc:postgresql://REPLACE_RDS_ENDPOINT:5432/pos_mk1"
  POS_REDIS_HOST: "REPLACE_ELASTICACHE_ENDPOINT"
  POS_REDIS_PORT: "6379"
  POS_ELASTICSEARCH_URIS: "http://REPLACE_EC2_SMALL_ELASTICSEARCH:9200"
  POS_SEARCH_ELASTICSEARCH_ENABLED: "true"
